### ISSUE TITLE
Logo design for shainet

### ISSUE THREAD

**Issue by psikoz** [NeuraLegion/shainet#88]
Hello, I want to make a logo contribution for you. I designed a logo. Please tell me what you think.

- brain: learn
- crystal

![shainet](https://user-images.githubusercontent.com/40601249/42277290-8c37496c-7f9f-11e8-985f-f3f373191cc1.jpg)

**Comment by ArtLinkov** [comment]
Hey @psikoz,
Thanks for taking the time to contribute to our project, we are happy to accept any help :smiley: 
First, let me say that we love the idea of using the Crystal logo with a brain :heart: 
If it is not too much trouble for you, I have a few suggestions.
- The crystal logo is pivoted to the left a little, so that the top part of the logo is a vertex and not the line. Would it be possible to tilt this logo as well?
- Also, building on the previous comment, it might look better if both the sides of the logo are separated between to vertices, not splitting the lines in half (note that if the white triangle gets in the way you can just make it smaller). If it looks too weird, you could try to make the brain polygony too

WDYT?

**Comment by psikoz** [comment]
Of course! :) I will edit it soon.

**Comment by psikoz** [comment]
hey @ArtLinkov  i made changes. how is it?

![sh1](https://user-images.githubusercontent.com/40601249/42410581-4ee7bf36-81f4-11e8-8edb-4e5d7077bfcf.jpg)

**Comment by ArtLinkov** [comment]
Looks awesome! :grin:
We liked the bottom one best, send us a PR and we will add it.
Thanks for this great contribution @psikoz

**Comment by psikoz** [comment]
I'm so glad you like it! :) I sent a pull-request.

**Comment by ArtLinkov** [comment]
PR accepted, closing issue
